In [2]:
import numpy as np
print(np.__version__)

1.12.1


In [3]:
# 2. How to create a 1D array
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 3. How to create a boolean array
print(np.ones((3,3)).astype(bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [10]:
# 4. How to extract items that satify a given condition from 1D array
arr = np.arange(0,10)
#result = np.where(arr % 2 != 0)
result = arr[arr % 2 != 0]

In [11]:
# 5. How to replace items that satify a condition with another value in numpy array
arr = np.arange(0,10)
arr[arr %2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [15]:
# 6. How to replace items that satisfy a condition without affecting the original array?
arr = np.arange(0,10)
out = np.where(arr % 2 != 0, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [16]:
# 7. How to reshape an array?
arr = np.arange(0,10)
out = arr.reshape(2,5)
print(out)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
# 8. How to stack two arrays vertically?

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
out = np.vstack([a,b])
print(a)
print(b)
print(out)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
# 9. How to stack two arrays horizontally?

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
out = np.hstack([a,b])
print(a)
print(b)
print(out)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [28]:
# 10. How to generate custom sequences in numpy without hardcoding?
arr = np.arange(1,4)
out = np.hstack([arr.repeat(3),np.tile(arr, 3)])
print(a)
print(out)

[1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [34]:
# 11. How to get the common items between two python numpy arrays?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
out = np.intersect1d(a,b)
print(out)

[2 4]


In [37]:
# 12. How to remove from one array those items that exist in another?
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
out = np.setdiff1d(a,b)
print(out)

[1 2 3 4]


In [39]:
# 13. How to get the positions where elements of two arrays match?
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# c = np.where((a - b) == 0)
print(np.where(a == b))

(array([1, 3, 5, 7]),)


In [40]:
# 14. How to extract all numbers between a given range from a numpy array?
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a[(a > 5) & (a < 10)])

[6 9]


In [5]:
# 15. How to make a python function that handles scalars to work on numpy arrays?

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

print(maxx(1, 5))

#def pair_max(x, y):
#    diff = x - y
#    diff[diff < 0] = 0
#    return diff + y
pair_max = np.vectorize(maxx, otypes = [float])   
    
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(pair_max(a, b))
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


5
[ 6.  7.  9.  8.  9.  7.  5.]


In [10]:
# 16. How to swap two columns in a 2d numpy array?
#  Q. Swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:, [1,0,2]])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [11]:
# 17. How to swap two rows in a 2d numpy array?
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[[1,0,2],:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [17]:
# 18. How to reverse the rows of a 2D array?
# Input
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[::-1,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [18]:
# 19. How to reverse the columns of a 2D array?
# Q. Reverse the columns of a 2D array arr.
# Input
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [5]:
# 20. How to create a 2D array containing random floats between 5 and 10?
# Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
arr = np.random.rand(5,3) * 5 + 5

rand_arr = np.random.uniform(5,10, size=(5,3))

print(rand_arr)

print(arr)

[[ 5.38   7.777  9.492]
 [ 9.406  5.482  6.574]
 [ 7.592  8.057  7.414]
 [ 7.488  5.228  9.177]
 [ 8.32   6.475  9.352]]
[[ 5.675  7.925  9.86 ]
 [ 6.913  7.053  6.726]
 [ 6.003  8.663  8.612]
 [ 9.289  9.225  5.239]
 [ 8.458  9.602  6.231]]


In [4]:
# 21. How to print only 3 decimal places in python numpy array?
# Q. Print or show only 3 decimal places of the numpy array rand_arr.
rand_arr = np.random.random((5,3))
np.set_printoptions(3)
print(rand_arr)

[[ 0.084  0.035  0.672]
 [ 0.637  0.024  0.657]
 [ 0.315  0.52   0.618]
 [ 0.434  0.632  0.791]
 [ 0.325  0.982  0.26 ]]


In [8]:
# 22. How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?
# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress = True, precision = 6)
print(rand_arr)
#> array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
#>        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
#>        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])


[[ 0.000543  0.000278  0.000425]
 [ 0.000845  0.000005  0.000122]
 [ 0.000671  0.000826  0.000137]]


In [9]:
# 23. How to limit the number of items printed in output of numpy array?
a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
#Desired Output:
#> array([ 0,  1,  2, ..., 12, 13, 14])
np.set_printoptions(threshold = 6)
print(a)

[ 0  1  2 ..., 12 13 14]


In [10]:
# 24. How to print the full numpy array without truncating
np.set_printoptions(threshold=6)
a = np.arange(15)
#> array([ 0,  1,  2, ..., 12, 13, 14])
#Desired Output:
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
np.set_printoptions(threshold = np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [22]:
# 25. How to import a dataset with numbers and texts keeping the text intact in python numpy?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
species = np.array([row[4] for row in iris_1d])
a = np.random.randn(6,6)
print(species[:10])

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa']


In [33]:
# 27. How to convert a 1d array of tuples to a 2d numpy array?
# Q. Convert the 1D iris to 2D array iris_2d by omitting the species text field.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
#data = np.array([row for row in iris_1d]).reshape(-1, len(iris_1d[0]))
#print(data.shape)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d.shape)

(150, 4)


In [36]:
# 28. How to compute the mean, median, standard deviation of a numpy array?
# Q. Find the mean, median, standard deviation of iris's sepallength (1st column)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
print(iris_2d.shape)
mean = np.mean(iris_2d[:,0])
median = np.median(iris_2d[:,0])
dev = np.std(iris_2d[:,0])
print(mean, median, dev)

(150, 4)
5.84333333333 5.8 0.825301291785


In [42]:
# 29. How to normalize an array so the values range exactly between 0 and 1?

#Q. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 
#   so that the minimum has value 0 and maximum has value 1.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
out = (sepallength - np.min(sepallength)) / np.max(sepallength)
print(out)



[ 0.101266  0.075949  0.050633  0.037975  0.088608  0.139241  0.037975
  0.088608  0.012658  0.075949  0.139241  0.063291  0.063291  0.        0.189873
  0.177215  0.139241  0.101266  0.177215  0.101266  0.139241  0.101266
  0.037975  0.101266  0.063291  0.088608  0.088608  0.113924  0.113924
  0.050633  0.063291  0.139241  0.113924  0.151899  0.075949  0.088608
  0.151899  0.075949  0.012658  0.101266  0.088608  0.025316  0.012658
  0.088608  0.101266  0.063291  0.101266  0.037975  0.126582  0.088608
  0.341772  0.265823  0.329114  0.151899  0.278481  0.177215  0.253165
  0.075949  0.291139  0.113924  0.088608  0.202532  0.21519   0.227848
  0.164557  0.303797  0.164557  0.189873  0.240506  0.164557  0.202532
  0.227848  0.253165  0.227848  0.265823  0.291139  0.316456  0.303797
  0.21519   0.177215  0.151899  0.151899  0.189873  0.21519   0.139241
  0.21519   0.303797  0.253165  0.164557  0.151899  0.151899  0.227848
  0.189873  0.088608  0.164557  0.177215  0.177215  0.240506  0.101

In [43]:
# 30. How to compute the softmax score?
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
out = np.exp(sepallength) / np.sum(np.exp(sepallength))
print(out)

[ 0.00222   0.001817  0.001488  0.001346  0.002008  0.002996  0.001346
  0.002008  0.001102  0.001817  0.002996  0.001644  0.001644  0.000997
  0.00447   0.004044  0.002996  0.00222   0.004044  0.00222   0.002996
  0.00222   0.001346  0.00222   0.001644  0.002008  0.002008  0.002453
  0.002453  0.001488  0.001644  0.002996  0.002453  0.003311  0.001817
  0.002008  0.003311  0.001817  0.001102  0.00222   0.002008  0.001218
  0.001102  0.002008  0.00222   0.001644  0.00222   0.001346  0.002711
  0.002008  0.01484   0.008144  0.013428  0.003311  0.009001  0.004044
  0.007369  0.001817  0.009947  0.002453  0.002008  0.00494   0.005459
  0.006033  0.003659  0.010994  0.003659  0.00447   0.006668  0.003659
  0.00494   0.006033  0.007369  0.006033  0.008144  0.009947  0.01215
  0.010994  0.005459  0.004044  0.003311  0.003311  0.00447   0.005459
  0.002996  0.005459  0.010994  0.007369  0.003659  0.003311  0.003311
  0.006033  0.00447   0.002008  0.003659  0.004044  0.004044  0.006668
  0.002

In [44]:
# 31. How to find the percentile scores of a numpy array?
# Q. Find the 5th and 95th percentile of iris's sepallength

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

np.percentile(sepallength, q = [5,95])


array([ 4.6  ,  7.255])

In [64]:
# 32. How to insert values at random positions in an array?
# Q . Insert np.nan values at 20 random positions in iris_2d dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

np.random.seed(100)
i, j = np.where(iris_2d)
output = np.copy(iris_2d)
output[np.random.choice(i, 20), np.random.choice(j, 20)] = np.nan


[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' nan b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' nan b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' nan b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' nan b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Iris-setosa']


In [75]:
# 33. How to find the position of missing values in numpy array?
# Q. Find the number and position of missing values in iris_2d's sepallength (1st column)
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
x, y= np.where(np.isnan(iris_2d))

SyntaxError: invalid syntax (<ipython-input-75-813ccf036acd>, line 5)

In [85]:
# 34. How to filter a numpy array based on two or more conditions?
# Q. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
output = np.copy(iris_2d)
condition  = (output[:,2] > 1.5) & (output[:,0] < 5)
print(output[condition])

[[ 4.8  3.4  1.6  0.2]
 [ 4.8  3.4  1.9  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 4.9  2.4  3.3  1. ]
 [ 4.9  2.5  4.5  1.7]]


In [95]:
# 35. How to drop rows that contain a missing value from a numpy array?
# Q. Select the rows of iris_2d that does not have any nan value.
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.choice(150, 20), np.random.choice(4, 1)] = np.nan
row, col = np.where(np.isnan(iris_2d))
row_d = np.delete(np.arange(150),row)
print(row_d.shape)

(130,)


In [106]:
# 36. How to find the correlation between two columns of a numpy array?
# Q. Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
print(len(iris_2d))

m_0 = np.mean(iris_2d[:,0])
m_2 = np.mean(iris_2d[:,2])
s_0 = np.std(iris_2d[:,0])
s_2 = np.std(iris_2d[:,2])

corr = np.sum(np.multiply((iris_2d[:,0] - m_0), (iris_2d[:,2] - m_2))) / len(iris_2d) / (s_0 * s_2)
corr_2 = np.corrcoef(iris_2d[:,0], iris_2d[:,2])
print(corr_2)
print(corr)

150
[[ 1.        0.871754]
 [ 0.871754  1.      ]]
0.871754157305


In [112]:
# 37. How to find if a given array has any null values?
# Q. Find out if iris_2d has any missing values.
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

result = np.sum(np.isnan(iris_2d))

result_2 = np.isnan(iris_2d).any()

print(result.astype(np.bool))
print(result_2)

False
False


In [117]:
# 38. How to replace all missing values with 0 in a numpy array?
# Q. Replace all ccurrences of nan with 0 in numpy array

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0
print(iris_2d)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0. ]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 0.   3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  0.   1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0. ]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [120]:
# 39. How to find the count of unique values in a numpy array?
# Q. Find the unique values and the count of unique values in iris's species

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

unique, count = np.unique(iris, return_counts = True)
print(unique)
print(count)

[b'0.1' b'0.2' b'0.3' b'0.4' b'0.5' b'0.6' b'1.0' b'1.1' b'1.2' b'1.3'
 b'1.4' b'1.5' b'1.6' b'1.7' b'1.8' b'1.9' b'2.0' b'2.1' b'2.2' b'2.3'
 b'2.4' b'2.5' b'2.6' b'2.7' b'2.8' b'2.9' b'3.0' b'3.1' b'3.2' b'3.3'
 b'3.4' b'3.5' b'3.6' b'3.7' b'3.8' b'3.9' b'4.0' b'4.1' b'4.2' b'4.3'
 b'4.4' b'4.5' b'4.6' b'4.7' b'4.8' b'4.9' b'5.0' b'5.1' b'5.2' b'5.3'
 b'5.4' b'5.5' b'5.6' b'5.7' b'5.8' b'5.9' b'6.0' b'6.1' b'6.2' b'6.3'
 b'6.4' b'6.5' b'6.6' b'6.7' b'6.8' b'6.9' b'7.0' b'7.1' b'7.2' b'7.3'
 b'7.4' b'7.6' b'7.7' b'7.9' b'Iris-setosa' b'Iris-versicolor'
 b'Iris-virginica']
[ 6 28  7  7  1  1  8  4  7 20 20 26 11  6 12  7  7  6  6 12  6 11  5  9 14
 10 27 12 13  8 12  8  4  4  7  5  6  4  5  3  8  9  7  7  9 11 14 17  6  3
  8 10 12 11 10  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1  1  4  1 50
 50 50]


In [144]:
# 40. How to convert a numeric to a categorical (text) array?
# Q. Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
# Less than 3 --> 'small'
# 3-5 --> 'medium'
# '>=5 --> 'large'

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

petal_length_bin = np.digitize(iris[:,2].astype('float'), [0,3,5,10])

load_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [load_map[x] for x in petal_length_bin]



['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large

In [152]:
# 41. How to create a new column from existing columns of a numpy array?
# Q. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Solution
# Compute volume
sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')
volume = (np.pi * petallength * (sepallength**2))/3


# Introduce new dimension to match iris_2d's
out = np.hstack([iris_2d, volume.reshape(-1,1)])
print(out.shape)

(150, 6)


In [166]:
# 42. How to do probabilistic sampling in numpy?

# Q. Randomly sample iris's species such that setose is twice the number of versicolor and virginica

# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# load_map = {0:"Iris-versicolor", 1:"Iris-virginica", 2: "Iris-setosa"}
# sequence = np.random.choice(3, len(iris), p = [0.5, 0.25, 0.25])

np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))

iris_out = iris[index, :]

#print(iris[index, :])
print(np.unique(iris_out[:,4], return_counts=True))

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'], dtype=object), array([77, 37, 36]))


In [172]:
# 43. How to get the second largest value of an array when grouped by another array?
# Q. What is the value of second longest petallength of species setosa

# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

filtered = iris[iris[:,4].astype(str) == 'Iris-setosa']
result = np.unique(np.sort(filtered[:,2].astype(np.float32)))[-2]
print(result)

1.7


In [173]:
# 44. How to sort a 2D array by a column
# Q. Sort the iris dataset based on sepallength column.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

output = iris[np.argsort(iris[:,0])]
print(output)

[[b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'4.4' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'3.0' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.5' b'2.3' b'1.3' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.6' b'1.0' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.6' b'3.2' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.3' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.1' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.9' b'2.4' b'3.3' b'1.0' b'Iris-versicolor']
 [b'4.9' b'2.5' b'4.5' b'1.7' b'Iris-virginica']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.

In [180]:
# 45. How to find the most frequent value in a numpy array?
# Q. Find the most frequent value of petal length (3rd column) in iris dataset.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

value, count = np.unique(iris[:,2], return_counts = True)
print(count)
f_v = value[np.argmax(count)]
print(f_v)


[ 1  1  2  7 12 14  7  4  2  1  2  2  1  1  1  3  5  3  4  2  4  8  3  5  4
  5  4  8  2  2  2  3  6  3  3  2  2  3  1  1  1  2  1]
b'1.5'


In [194]:
# 46. How to find the position of the first occurrence of a value greater than a given value?
# Q. Find the position of the first occurrence of a value greater than 1.0 in petalwidth 4th column of iris dataset.

# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

print(np.argwhere(iris[:,3].astype('float') > 1.0)[0])

[50]


In [195]:
# 47. How to replace all values greater than a given value to a given cutoff?
# Q. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.
# Input
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)

print(np.clip(a, a_min = 10, a_max = 30))


[ 27.63  14.64  21.8   30.    10.    10.    30.    30.    10.    29.18  30.
  11.25  10.08  10.    11.77  30.    30.    10.    30.    14.43]


In [213]:
# 48. How to get the positions of top n values from a numpy array?
# Q. Get the positions of top 5 maximum values in a given array a.

np.random.seed(100)
a = np.random.uniform(1,50, 20)

print(np.argpartition(-a, 4)[:5])

[15 10  3  7 18]


In [229]:
# 49. How to compute the row wise counts of all possible values in an array?
#Q. Compute the counts of unique values row-wise.

#Input:

np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

# arr
# > array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
# >        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
# >        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
# >        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
# >        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
# >        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
# Desired Output:

# > [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
# >  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
# >  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
# >  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
# >  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
# >  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

unique, count = np.unique(arr[0,:], return_counts = True)
print(arr[0])
print(unique)
print(count)

def counts_of_all_values_rowwise(arr2d):
    num_counts_array = [np.unique(row, return_counts = True) for row in arr2d]
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

print(counts_of_all_values_rowwise(arr))
#print(np.unique(arr))

[9 9 4 8 8 1 5 3 6 3]
[1 3 4 5 6 8 9]
[1 2 1 1 1 2 2]
[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0], [2, 1, 3, 0, 1, 0, 1, 0, 1, 1], [0, 3, 0, 2, 3, 1, 0, 1, 0, 0], [1, 0, 2, 1, 0, 1, 0, 2, 1, 2], [2, 2, 2, 0, 0, 1, 1, 1, 1, 0], [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]


In [242]:
# 50. How to convert an array of arrays into a flat 1d array?
# Difficulty Level: 2

# Q. Convert array_of_arrays into a flat linear 1d array.

# Input:

# Input:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
#> array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])], dtype=object)
# Desired Output:
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

result = np.array([a for arr in array_of_arrays for a in arr])
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [250]:
# 51. How to generate one-hot encodings for an array in numpy?
# Difficulty Level L4

# Q. Compute the one-hot encodings (dummy binary variables for each unique value in the array)

# Input:

np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
#> array([2, 3, 2, 2, 2, 1])
# Output:

#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])

one_hot = np.zeros([len(arr), np.max(arr)])
for i in range(6):
    one_hot[i, arr[i] - 1] = 1
print(one_hot)

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]]


In [252]:
# 52. How to create row numbers grouped by a categorical variable?
# Difficulty Level: L3

# Q. Create row numbers grouped by a categorical variable. Use the following sample from iris species as input.

# Input:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))

#> array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
#>        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],
#>       dtype='<U15')
# Desired Output:

#> [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]

print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])

[0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]
